### ISSUE TITLE
FIQ interrupt

### ISSUE THREAD

**Issue by Aptahar** [OpenNuvoton/NUC980-linux-5.10.y#21]
How can I configure FIQ interrupt?
In en-us--NUC980_Linux_5.10_BSP_User_Manual_EN.pdf on 45 page there is manual that  says I need to enable "Nuvoton NUC980 FIQ support" in menuconfig. But there is no option like that.
Also I've search CONFIG_NUC980_FIQ, no success.

**Comment by ychuang3** [comment]
Apologies for the documentation error; we will correct it in the next version.

In Linux-4.4, we did attempt to support FIQ, but some users encountered difficult-to-resolve issues during its use, so we no longer recommend it to customers. Additionally, the NUC980 platform, after being ported to Linux-5.10, does not support FIQ at all.
