### ISSUE TITLE
adc touch ask

### ISSUE THREAD

**Issue by flyxx2** [OpenNuvoton/NUC980-linux-5.10.y#9]
nuvoton,pins = 
<1 0x4 0x8 0 1 0x5 0x8 0 1 0x6 0x8 0 1 0x7 0x8 0 >;  PB[4:7]
in Nuc980_linux_enviroment_on_vmware.pdf     nuc980-iot-g2d example

if I change to PB[0:3] didn't work . only at PB[4:7] can run. How did I modify

**Comment by ychuang3** [comment]
Because the dts describes the board, you have the iot-g2d board, right?
Please check its schematic. Is the ADC touch connected to PB.4 ~ PB.7 or PB.0 ~ PB.3?
Have you made any jumper modifications to the ADC wiring?

**Comment by flyxx2** [comment]
tks @ychuang3 relay soon.
I check the two vesrion of TFT V1.5 and V1.3 at Nuvoton production.
TFT V1.5 for NUC980-IOT-G2D, have two statament jumper (NUC980、M0/M23x)    ->  need to PB[4:7]
TFT V1.3 for M32KIAAE, only at PB[0:4]

Yeah, What I mean. If you change the TFT screen. (NUC980-IOT-G2 + TFT V1.3). it can display but didn't input the touch.

So, Can you tell me how to modify. Maybe need to change pin name at linux kernel driver

**Comment by ychuang3** [comment]
It's apparent that these two TFT LCDs are not entirely compatible, especially in the touch aspect, right? Why did you choose to do this?

**Comment by flyxx2** [comment]
This is a wrong layout at PB[0:4]. it didn't to change the pin right? 
By the way, the gpio should be changed any unpopulated. So I asked the question.

**Comment by ychuang3** [comment]
I've checked the schematic of the IoT-G2D, and the ADC touch is connected to PB.4 ~ PB.7. Therefore, the dts configuration is completely correct, and this has been tested.
If you use the TFT V1.5 board, everything should work fine. However, if you use the TFT V1.3 board, it's not compatible with the NUC980 IoT-G2D board, so you'll need to modify the TFT V1.3 board.
Therefore, please use the TFT V1.5 board.
